import './globals.scss';
import { Geist, Geist_Mono } from 'next/font/google';

// Definition of fonts
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Definition of render method for components in app --> dynamic: upon user-input only component that changes
export const dynamic = 'force-dynamic';

// Definition of app-description in browser tab
export const metadata = {
  title: {
    default: 'App | Product Planner ',
    template: '%s | Product Planner',
  },
  description: 'Generated by Juergen Aichinger',
};

// Definition of app´s root layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
